GET {{baseUrl}}/books/
###

GET {{baseUrl}}/books/62c71f42416a6c08d3dfa764
###

POST {{baseUrl}}/books/
Content-Type: application/json

{
  "title": "APITitle",
  "description": "This is my title from API",
  "authors": "stPitty",
  "favorite": "Number one",
  "fileCover": "SomeText",
  "fileName": "Okay"
}
###

PUT {{baseUrl}}/books/62c71cc2fe1d6c1ce39a063e
Content-Type: application/json

{
  "title": "SDADSADASDSAD"
}
###

DELETE {{baseUrl}}/books/62c71f8f416a6c08d3dfa76b
###

POST {{baseUrl}}/user/login/
Content-Type: application/json

{
  "id": 12,
  "mail": "example@mail.com"
}
###

POST {{baseUrl}}/books/upload-book/
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="fileBook"; filename="demoid.txt";
< ./input.txt --boundary--
###

GET {{baseUrl}}/books/demoid.txt/download/
###
